# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 23:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('upload_time', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_logo', models.ImageField(default='logo_none.jpg', upload_to='')),
                ('user_gender', models.CharField(blank=True, max_length=6)),
                ('user_birthday_day', models.CharField(blank=True, max_length=2)),
                ('user_birthday_month', models.CharField(blank=True, max_length=2)),
                ('user_birthday_year', models.CharField(blank=True, max_length=4)),
                ('user_country', models.CharField(blank=True, max_length=100)),
                ('user_city', models.CharField(blank=True, max_length=50)),
                ('user_mobile_number', models.CharField(blank=True, max_length=10)),
                ('user_about_me', models.CharField(blank=True, max_length=999999)),
                ('user_education', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='photologo',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile'),
        ),
    ]
