# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_about_me',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_birthday_day',
            new_name='birthday_day',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_birthday_month',
            new_name='birthday_month',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_birthday_year',
            new_name='birthday_year',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_education',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_mobile_number',
            new_name='mobile_number',
        ),
    ]
