# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180125_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday_day',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday_month',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday_year',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
        ),
    ]
