# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('artist', models.CharField(default='', max_length=100)),
                ('duration', models.FloatField(default=0)),
                ('source', models.FileField(default=1, upload_to='')),
            ],
        ),
    ]
