# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='unique_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
