# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_unique_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='unique_name',
        ),
    ]
