# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_song_unique_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='album',
            name='logo',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
        ),
    ]
