# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_author_id', models.CharField(default='', max_length=255)),
                ('user_friend_id', models.CharField(default='', max_length=255)),
                ('logo', models.ImageField(default=1, upload_to='')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='account.UserProfile')),
                ('friend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='account.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(default='', max_length=99999)),
                ('author', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('author_fn_ln', models.CharField(default='', max_length=100)),
                ('author_logo', models.FileField(default=1, upload_to='')),
                ('author_id', models.CharField(default='', max_length=100)),
                ('chat_room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoom')),
            ],
        ),
    ]
