# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:30
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(default='', max_length=99999)),
                ('author', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('author_fn_ln', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_logo', models.FileField(upload_to='')),
                ('user_background_photo', models.FileField(upload_to='')),
                ('user_gender', models.CharField(default='', max_length=6)),
                ('user_birthday_day', models.IntegerField(default=0)),
                ('user_birthday_month', models.CharField(default='', max_length=30)),
                ('user_birthday_year', models.IntegerField(default=0)),
                ('user_country', models.CharField(default='', max_length=30)),
                ('user_city', models.CharField(default='', max_length=50)),
                ('user_mobile_number', models.CharField(default='', max_length=10)),
                ('user_about_me', models.CharField(default='', max_length=999999)),
                ('user_education', models.CharField(default='', max_length=100)),
                ('user_status', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
