# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='user_author_id',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user_friend_id',
        ),
    ]
