# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg',
            field=models.CharField(default='', max_length=99999),
        ),
    ]
