# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180126_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='author_username',
        ),
    ]
