# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('user_1', models.CharField(default='', max_length=100)),
                ('user_2', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
