# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-28 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180127_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
