# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20180128_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author_username',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_message',
            field=models.CharField(default='', max_length=9999999),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.CharField(default='', max_length=9999999),
        ),
    ]
