# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chat_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoom'),
        ),
    ]
