# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatroom_has_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_unread',
            field=models.BooleanField(default=True),
        ),
    ]
