# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_userprofile_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author_logo',
            field=models.FileField(default=1, upload_to=''),
        ),
    ]
