# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_author_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
