# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-11 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_is_unread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author_fn_ln',
            new_name='author_initials',
        ),
        migrations.AlterField(
            model_name='message',
            name='author_id',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
