# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-11 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20180311_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author_id',
            field=models.IntegerField(default=0),
        ),
    ]
