# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_userprofile_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_background_photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
