# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20180311_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='last_message',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_message_id',
            field=models.IntegerField(default=0),
        ),
    ]
