# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20180320_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
