# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20170817_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('upload_time', models.CharField(default='', max_length=100)),
                ('likes_amount', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('upload_time', models.CharField(default='', max_length=100)),
                ('likes_amount', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.UserProfile')),
            ],
        ),
    ]
