# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_photobackground_photologo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photobackground',
            name='likes_amount',
        ),
        migrations.RemoveField(
            model_name='photologo',
            name='likes_amount',
        ),
    ]
