# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20170817_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='chat.UserProfile'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='chat.UserProfile'),
        ),
    ]
