# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20170817_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='logo',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
