# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_remove_userprofile_user_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_background_photo',
        ),
    ]
