# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_auto_20170826_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_logo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
