# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_auto_20170826_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_logo',
            field=models.ImageField(default='logo_none.png', upload_to=''),
        ),
    ]
