# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_auto_20170826_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_birthday_day',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_birthday_month',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_birthday_year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
