# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_auto_20170828_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photobackground',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_background_photo',
        ),
        migrations.DeleteModel(
            name='PhotoBackground',
        ),
    ]
